
export enum ACTION_TYPE {
  // for user
  SET_USER = 'SET_USER',
  // for cart
  TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN',
  ADD_ITEM = 'ADD_ITEM',
  SHOW_CART_DROPDOWN = 'SHOW_CART_DROPDOWN',
  GET_CART_ITEM_COUNT =  'GET_CART_ITEM_COUNT',
  UPDATE_QUANTITY = 'UPDATE_QUANTITY',

  // for directory
  ADD_DIRECTORY = 'ADD_DIRECTORY',


  // for shop collection
  UPDATE_SHOP_COLLECTION = 'UPDATE_SHOP_COLLECTION',
  FETCH_SHOP_COLLECTION_START = 'FETCH_SHOP_COLLECTION_START',
  FETCH_SHOP_COLLECTION_SUCCESS = 'FETCH_SHOP_COLLECTION_SUCCESS',
  FETCH_SHOP_COLLECTION_FAILURE = 'FETCH_SHOP_COLLECTION_FAILURE',
}